import { inject, injectable } from 'tsyringe';
import { IGoogleAuthUseCase } from '../../interfaces/auth/IGoogleAuthUseCase';
import { IGoogleAuthService } from '../../interfaces/auth/IGoogleAuthService';
import { IUserRepository } from '../../../domain/repositories/IUserRepository';
import { IJwtService } from '../../../domain/services/IJwtService';
import { LoginResponse } from '../../interfaces/auth/ILoginUseCase';
import { User } from '../../../domain/entities/User';
import { UserRole } from '../../../constants/enums/UserRole';
import { WalletModel } from '../../../infrastructure/database/models/WalletModel';

@injectable()
export class GoogleAuthUseCase implements IGoogleAuthUseCase {
    constructor(
        @inject('IGoogleAuthService') private googleAuthService: IGoogleAuthService,
        @inject('IUserRepository') private userRepository: IUserRepository,
        @inject('IJwtService') private jwtService: IJwtService
    ) { }

    async execute(credential: string): Promise<LoginResponse> {
        if (!credential) {
            throw new Error('Google token is required');
        }

        // 1. Verify token with Google API
        const payload = await this.googleAuthService.verifyGoogleToken(credential);
        const normalizedEmail = payload.email.trim().toLowerCase();

        // 2. Search for existing user by email
        let user = await this.userRepository.findByEmail(normalizedEmail);

        if (user) {
            // If user exists, update/link googleId and picture if not already linked
            const updateFields: any = {};
            if (!user.googleId) {
                updateFields.googleId = payload.googleId;
            }
            if (!user.imageUrl && payload.picture) {
                updateFields.imageUrl = payload.picture;
            }

            if (Object.keys(updateFields).length > 0 && user.id) {
                await this.userRepository.findByIdAndUpdate(user.id, updateFields);
                const updatedUser = await this.userRepository.findById(user.id);
                if (updatedUser) {
                    user = updatedUser;
                }
            }
        } else {
            // Create new user for Google Sign-In
            const namePart = (payload.name || 'USER').substring(0, 4).toUpperCase().replace(/[^A-Z]/g, 'X');
            const randPart = Math.floor(1000 + Math.random() * 9000).toString();
            const referralId = namePart + randPart;

            const newUser = new User(
                '', // id generated by DB
                normalizedEmail,
                payload.name, // displayName
                payload.name, // username
                undefined, // phoneNumber
                undefined, // no password for Google user
                UserRole.USER,
                true, // verified = true for Google users
                payload.picture,
                referralId,
                undefined, // referredBy
                [], // addresses
                new Date(),
                new Date(),
                false, // isInfluencer
                undefined,
                null,
                undefined,
                undefined,
                undefined,
                'Active',
                0,
                undefined,
                undefined,
                0,
                0,
                undefined,
                undefined,
                undefined,
                undefined,
                undefined,
                undefined,
                undefined,
                undefined,
                null,
                null,
                payload.googleId,
                'google'
            );

            user = await this.userRepository.save(newUser);

            // Ensure Wallet creation for new user
            try {
                const existingWallet = await WalletModel.findOne({ userId: user.id });
                if (!existingWallet) {
                    await WalletModel.create({ userId: user.id });
                }
            } catch (err) {
                console.error('[GoogleAuthUseCase] Error creating wallet for user:', err);
            }
        }

        // 3. Generate JWT tokens
        const jwtPayload = {
            id: user.id,
            email: user.email,
            role: user.role,
            isInfluencer: user.isInfluencer
        };

        const accessToken = this.jwtService.generateAccessToken(jwtPayload);
        const refreshToken = this.jwtService.generateRefreshToken(jwtPayload);

        // Remove password if present before returning user object
        const { password: _, ...userWithoutPassword } = user;

        return {
            user: userWithoutPassword as any,
            accessToken,
            refreshToken
        };
    }
}
